### ISSUE TITLE
fix: incompatible version with mason 0.1.0

### ISSUE THREAD

**Issue by TimoSchmuck** [VeryGoodOpenSource/r13n#78]
### Description

I get the following error when executing "mason make r13n --on-conflict overwrite"
```
The current mason version is 0.1.0.
Because r13n requires mason version >=0.1.0-dev.28 <0.1.0, version solving failed.
```
I've followed the instructions as described in the installation but got this error. Can you help?

### Steps To Reproduce

Execute "mason make r13n --on-conflict overwrite"

### Expected Behavior

No error. 

### Additional Context

YAML File
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # for internationalization
    sdk: flutter         #
  intl: ^0.19.0
  r13n: 0.1.0-dev.3
  [...]
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.3, on macOS 15.2 24C101 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```
